import {test} from 'node:test'
import assert from 'node:assert/strict'
import {newsArticleUrl} from '../src/main/security.mjs'
import {renderNews} from '../src/renderer/news-view.mjs'
import {renderLife,renderProfile} from '../src/renderer/life-view.mjs'
class Node {constructor(tag){this.tag=tag;this.children=[];this.listeners={};this.dataset={}}append(...c){this.children.push(...c)}setAttribute(k,v){this[k]=v}addEventListener(k,v){this.listeners[k]=v}}
function harness(t){const old=globalThis.document;t.after(()=>{globalThis.document=old});globalThis.document={createElement:tag=>new Node(tag)};const panel=new Node('div'),buttons=[],calls=[];const button=(label,action,parent)=>{const b=new Node('button');b.textContent=label;b.action=action;buttons.push(b);parent.append(b);return b};return {panel,buttons,calls,button,command:async(...args)=>{calls.push(args)},local:{},rerender(){},profile(){},openArticle:async url=>{calls.push(['open',url])}}}
test('links reject non-web schemes, credentials and local addresses',()=>{for(const u of ['file:///tmp/x','javascript:alert(1)','https://user:pw@example.com','http://127.0.0.1','http://[::1]/'])assert.throws(()=>newsArticleUrl(u));assert.equal(newsArticleUrl('https://www.bbc.com/news/one'),'https://www.bbc.com/news/one')})
test('reading and saving news are explicit and do not write profile facts',async t=>{const h=harness(t);renderNews(h.panel,{...h,news:{enabled:true,mode:'personalized',pending:0,sources:[{id:'bbc',name:'BBC'}],interests:[],items:[{id:'a',source_id:'bbc',title:'Actual news',summary:'Excerpt',url:'https://www.bbc.com/news/a',ranking:null}],saved:[]}});assert.equal(h.calls.length,0);await h.buttons.find(b=>b.textContent==='阅读原文').action();await h.buttons.find(b=>b.textContent==='收藏').action();assert.deepEqual(h.calls,[['open','https://www.bbc.com/news/a'],['news.action',{action:'read',id:'a',value:true}],['news.action',{action:'save',id:'a',value:true}]])})
test('ideas convert explicitly and goals show zero denominator honestly',async t=>{const h=harness(t);const idea={id:'i',kind:'idea',title:'A',note:'B',version:1,status:'active'};renderLife(h.panel,{...h,kind:'idea',state:{ideas:[idea],todos:[],goals:[]},delegate(){}});await h.buttons.find(b=>b.textContent==='转为目标').action();assert.deepEqual(h.calls[0],['life.mutate',{op:'convert',id:'i',target:'goal',expected_version:1}]);assert.equal(h.calls.length,1)})
test('profile uses news canonical interests, no collection is copied into life profile',async t=>{const h=harness(t);renderProfile(h.panel,{...h,state:{profile:{version:2,about:'Me'}},news:{enabled:true,explore:false,interests:[{id:'ai',text:'AI',weight:1}]},showMemory(){}});await h.buttons.find(b=>b.textContent==='保存兴趣与开关').action();assert.equal(h.calls[0][0],'news.configure');assert.deepEqual(h.calls[0][1].interests,['AI'])})
